House_Utiliti_Service/Controllers/WorksController.cs
using House_Utiliti_Service.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using House_Utiliti_Service.ViewModel;
using System.IO;
using System.Threading;

namespace House_Utiliti_Service.Controllers
{
    [Authorize]
    public class WorksController : Controller
    {
        USDbContext db = new USDbContext();
        public ActionResult Index()
        {
            return View(db.works.Include(b =>b.WorkArea).ToList());
        }
        public ActionResult Create()
        {
            ViewBag.workareas = db.workAreas.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Create(WorkInputModel w)
        {
            if (ModelState.IsValid)
            {
                var work = new Work
                {
                    CustomerName = w.CustomerName,
                    CustomerAddress = w.CustomerAddress,
                    WorkDescription=w.WorkDescription,
                    StartDate=w.StartDate,
                    EndDate=w.EndDate,
                    WorkAreaId = w.WorkAreaId
                };
                db.works.Add(work);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.workarea = db.workAreas.ToList();
            return View(w);
        }
        public ActionResult Edit(int id)
        {
            var t = db.works.First(x => x.WorkId == id);
            ViewBag.workAreas = db.workAreas.ToList();
            return View(new WorkEditModel { WorkId = t.WorkId, CustomerName = t.CustomerName, CustomerAddress = t.CustomerAddress,WorkDescription=t.WorkDescription,StartDate=t.StartDate,EndDate=t.EndDate ,WorkAreaId = t.WorkAreaId });
        }
        [HttpPost]
        public ActionResult Edit(WorkEditModel t)
        {
            Thread.Sleep(2000);
            var work = db.works.First(x => x.WorkId == t.WorkId);
            if (ModelState.IsValid)
            {


                work.CustomerName = t.CustomerName;
                work.CustomerAddress = t.CustomerAddress;
                work.WorkDescription = t.WorkDescription;
                work.StartDate = t.StartDate;
                work.EndDate = t.EndDate;
                
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.works = db.works.ToList();
            return View(t);
        }
        public ActionResult Delete(int id)
        {
            return View(db.works.Include(x => x.WorkArea).First(x => x.WorkId == id));
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            Work t = new Work { WorkId = id };
            db.Entry(t).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

}

House_Utiliti_Service/Views/Works/Create.cshtml
@model House_Utiliti_Service.ViewModel.WorkInputModel
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("Create", "Works", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.WorkAreaId, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.DropDownListFor(x => x.WorkAreaId, new SelectList(ViewBag.workAreas, "WorkAreaId", "WorkAreaName"), "Select", new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.WorkAreaId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.CustomerName, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.CustomerName, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.CustomerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.CustomerAddress, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.CustomerAddress, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.CustomerAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.WorkDescription, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.WorkDescription, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.WorkDescription, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.StartDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.StartDate, new { @class = "form-control form-control-sm date" })
                    @Html.ValidationMessageFor(x => x.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.EndDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.EndDate, new { @class = "form-control form-control-sm date" })
                    @Html.ValidationMessageFor(x => x.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">

                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
</div>
@*@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

}*@
@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
    </script>
    }

House_Utiliti_Service/Views/Works/Delete.cshtml
@model House_Utiliti_Service.Models.Work
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-12">
        <h3>Are you sure to delete?</h3>

        @Html.HiddenFor(x => x.WorkId)
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.WorkArea, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.WorkArea.WorkAreaName)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.CustomerName, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.CustomerName)

            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.CustomerAddress, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.CustomerAddress)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.WorkDescription, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.WorkDescription)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.StartDate, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.StartDate)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.EndDate, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.EndDate)
            </div>
        </div>

        @using (Html.BeginForm("Delete", "Works", new { id = Model.WorkId }, FormMethod.Post))
        {

            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-danger">Confirm Delete</button>

            </div>
        }
        <div class="col-12">

            @Html.ActionLink("Back to list", "Index")
        </div>
    </div>
</div>

House_Utiliti_Service/Views/Works/Edit.cshtml
@model House_Utiliti_Service.ViewModel.WorkEditModel
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("Edit", "Works", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.WorkId)

            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.CustomerName, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.CustomerName, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.CustomerName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.CustomerAddress, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.CustomerAddress, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.CustomerAddress, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.WorkDescription, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.WorkDescription, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.WorkDescription, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.WorkAreaId, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.DropDownListFor(x => x.WorkAreaId, new SelectList(ViewBag.workAreas, "WorkAreaId", "WorkAreaName"), "Select", new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.WorkAreaId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.StartDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.StartDate, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.StartDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.EndDate, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.EndDate, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.EndDate, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">

                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        }
    </div>
    <div class="col-12">

        @Html.ActionLink("Back to list", "Index")
    </div>
</div>
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>



}

House_Utiliti_Service/Views/Works/Index.cshtml
@model IEnumerable<House_Utiliti_Service.Models.Work>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3>Products</h3>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Add New", "Create", "Works", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead class="bg-secondary">
                <tr>
                   
                    <th>@Html.DisplayNameFor(x => x.WorkArea.WorkAreaName)</th>
                    <th>@Html.DisplayNameFor(x => x.CustomerName)</th>

                    <th>@Html.DisplayNameFor(x => x.CustomerAddress)</th>
                    <th>@Html.DisplayNameFor(x => x.WorkDescription)</th>
                    <th>@Html.DisplayNameFor(x => x.StartDate)</th>
                    <th>@Html.DisplayNameFor(x => x.EndDate)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    <tr>

                        <td>@Html.DisplayFor(x => b.WorkArea.WorkAreaName)</td>
                        <td>@Html.DisplayFor(x => b.CustomerName)</td>
                        <td>@Html.DisplayFor(x => b.CustomerAddress)</td>
                        <td>@Html.DisplayFor(x => b.WorkDescription)</td>
                        <td>@Html.DisplayFor(x => b.StartDate)</td>
                        <td>@Html.DisplayFor(x => b.EndDate)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Works", new { id = b.WorkId }, new { @class = "btn btn-secondary btn-sm" })
                            <a href="@Url.Action("Delete", "Works", new {id=b.WorkId})" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>