House_Utiliti_Service/ViewModels/WorkerViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace House_Utiliti_Service.ViewModels
{
    public class WorkerViewModel
    {
        [Required]
        public int WorkerId { get; set; }
        public string WorkerName { get; set; }

        public String Phone { get; set; }

        public decimal Payrate { get; set; }

        public bool IsRunning { get; set; }
    }
}

House_Utiliti_Service/Controllers/WorkersController.cs
using House_Utiliti_Service.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace House_Utiliti_Service.Controllers
{
    [Authorize]
    public class WorkersController : Controller
    {
        USDbContext db = new USDbContext();
        public ActionResult Index()
        {
            return View(db.workers.Include(b => b.workerPayments).ToList());
        }
        public ActionResult Create()
        {
            return View();
        }
        public PartialViewResult CreateWorker()
        {
            return PartialView("_CreateWorker");
        }
        [HttpPost]
        public PartialViewResult CreateWorker(Worker w)
        {
            if (ModelState.IsValid)
            {
                db.workers.Add(w);
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;
            return View();
        }
        public PartialViewResult EditWorker(int id)
        {
            var b = db.workers.First(x => x.WorkerId == id);
            return PartialView("_EditWorker", b);
        }
        [HttpPost]
        public PartialViewResult EditWorker(Worker w)
        {
            Thread.Sleep(4000);
            if (ModelState.IsValid)
            {
                db.Entry(w).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Success");
            }
            return PartialView("_Fail");
        }
        public ActionResult Delete(int id)
        {
            return View(db.workers.First(x => x.WorkerId == id));
        }
        [HttpPost]
        [ActionName("Delete")]
        public ActionResult DoDelete(int workerId)
        {
            var b = new Worker { WorkerId = workerId };
            db.Entry(b).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

House_Utiliti_Service/Views/Workers/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <div id="spinner" style="display:none">
            <div class="d-flex align-items-center text-primary">
                <span>Loading...</span>
                <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
            </div>
        </div>
    </div>
    <div class="col-12 px-5">
        <h3>Add new Worker</h3>
        @Html.Action("CreateWorker")
    </div>
    <div class="col-12">

        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
    </script>
}

House_Utiliti_Service/Views/Workers/Delete.cshtml
@model House_Utiliti_Service.Models.Worker
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-12">
        <h3>Cofirm delete</h3>
    </div>
    <div class="col-12">
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.WorkerName, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.WorkerName)

            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.Phone, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.Phone)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.Payrate, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.Payrate)
            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.IsRunning, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.IsRunning)
            </div>
        </div>
        <div class="form-group row mb-1">

            @using (Html.BeginForm())
            {
                @Html.HiddenFor(x => x.WorkerId)
                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-danger">Confirm Delete</button>
                </div>
            }
        </div>
    </div>
    <div class="col-12">

        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

House_Utiliti_Service/Views/Workers/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        <div id="alert"></div>
        <div id="spinner" style="display:none">
            <div class="d-flex align-items-center text-primary">
                <span>Loading...</span>
                <div class="spinner-border ms-auto" role="status" aria-hidden="true"></div>
            </div>
        </div>
    </div>
    <div class="col-12">
        <h3>Edit Worker</h3>
        @Html.Action("EditWorker", new { id = ViewBag.Id })
    </div>
    <div class="col-12">

        @Html.ActionLink("Back to list", "Index")
    </div>
</div>

@section styles{
    <link href="~/Content/bootstrap-datepicker.standalone.css" rel="stylesheet" />
}
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
    <script>
        function onSuccess() {
            $("#f").trigger('reset');
        }
        $(".date").datepicker({
            format: "yyyy-mm-dd"
        });
        $("#OrderDate").val(formatDate($("#OrderDate").val()));
        if ($("#ReceiveDate").val() != "") {
            $("#ReceiveDate").val(formatDate($("#ReceiveDate").val()));
        }
        function formatDate(date) {
            var d = new Date(date),
                month = '' + (d.getMonth() + 1),
                day = '' + d.getDate(),
                year = d.getFullYear();

            if (month.length < 2)
                month = '0' + month;
            if (day.length < 2)
                day = '0' + day;

            return [year, month, day].join('-');
        }
    </script>
}

House_Utiliti_Service/Views/Workers/Index.cshtml
@model IEnumerable<House_Utiliti_Service.Models.Worker>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-8">
        <h3>Workers</h3>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Add New", "Create", "Workers", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead class="bg-secondary">
                <tr>

                    <th>@Html.DisplayNameFor(x => x.WorkerName)</th>
                    <th>@Html.DisplayNameFor(x => x.Phone)</th>
                    <th>@Html.DisplayNameFor(x => x.Payrate)</th>
                    <th>@Html.DisplayNameFor(x => x.IsRunning)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(x => b.WorkerName)</td>
                        <td>@Html.DisplayFor(x => b.Phone)</td>
                        <td>@Html.DisplayFor(x => b.Payrate)</td>
                        <td>@Html.DisplayFor(x => b.IsRunning)</td>
                        <td>
                            @Html.ActionLink("Edit", "Edit", "Workers", new { id = b.WorkerId }, new { @class = "btn btn-secondary btn-sm" })
                            <a href="@Url.Action("Delete", "Workers", new {id=b.WorkerId})" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

House_Utiliti_Service/Views/Workers/_CreateWorker.cshtml
@model House_Utiliti_Service.Models.Worker
@using (Ajax.BeginForm("CreateWorker", "Workers", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    LoadingElementId = "spinner",
    OnSuccess = "onSuccess"
}, new { id = "f" }))
{
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.WorkerName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.WorkerName, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.WorkerName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Phone, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Phone, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.Phone, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Payrate, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Payrate, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.Payrate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.IsRunning, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.CheckBoxFor(x => x.IsRunning, new { @class = "form-check" })
            @Html.ValidationMessageFor(x => x.IsRunning, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">

        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}

House_Utiliti_Service/Views/Workers/_EditWorker.cshtml
@model House_Utiliti_Service.Models.Worker
@using (Ajax.BeginForm("EditWorker", "Workers", new { }, new AjaxOptions
{
    HttpMethod = "Post",
    InsertionMode = InsertionMode.Replace,
    UpdateTargetId = "alert",
    LoadingElementId = "spinner"

}, new { id = "f" }))
{
    @Html.HiddenFor(x => x.WorkerId)
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.WorkerName, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.WorkerName, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.WorkerName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Phone, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Phone, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.Phone, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.Payrate, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.TextBoxFor(x => x.Payrate, new { @class = "form-control form-control-sm" })
            @Html.ValidationMessageFor(x => x.Payrate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group row mb-1">
        @Html.LabelFor(x => x.IsRunning, new { @class = "col-form-label col-form-label-sm col-2" })
        <div class="col-4">
            @Html.CheckBoxFor(x => x.IsRunning, new { @class = "form-check" })
            @Html.ValidationMessageFor(x => x.IsRunning, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group row mb-1">

        <div class="col-4 offset-2">
            <button type="submit" class="btn btn-primary">Save</button>
        </div>
    </div>
}