House_Utiliti_Service/Controllers/WorkerPaymentsController.cs
using House_Utiliti_Service.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using House_Utiliti_Service.ViewModels;
using System.Threading;

namespace House_Utiliti_Service.Controllers
{
    [Authorize]
    public class WorkerPaymentsController : Controller
    {
        USDbContext db = new USDbContext();
        // GET: Trainees
        public ActionResult Index()
        {
            return View(db.workerPayments.Include(b => b.Worker).ToList());
        }
        public ActionResult Create()
        {
            ViewBag.workers = db.workers.ToList();
            return View();
        }
        [HttpPost]
        public ActionResult Create(PaymentInputModel t)
        {
            if (ModelState.IsValid)
            {
                var WorkerPayment = new WorkerPayment
                {
                    TotalWorkHour = t.TotalWorkHour,
                    TotalPayment = t.TotalPayment,
                    WorkerId = t.WorkerId
                };
                string ext = Path.GetExtension(t.WorkerPictur.FileName);
                string f = Guid.NewGuid() + ext;
                t.WorkerPictur.SaveAs(Server.MapPath("~/Uploads/") + f);
                WorkerPayment.WorkerPictur = f;
                db.workerPayments.Add(WorkerPayment);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.workers = db.workers.ToList();
            return View(t);
        }
        public ActionResult Edit(int id)
        {
            var t = db.workerPayments.First(x => x.PaymentId == id);
            ViewBag.workers = db.workers.ToList();
            ViewBag.CurrentPic = t.WorkerPictur;
            return View(new PaymentEditModel { PaymentId = t.PaymentId, TotalWorkHour = t.TotalWorkHour, TotalPayment = t.TotalPayment, WorkerId = t.WorkerId });
        }
        [HttpPost]
        public ActionResult Edit(PaymentEditModel t)
        {
            Thread.Sleep(2000);
            var workerPayments = db.workerPayments.First(x => x.WorkerId == t.WorkerId);
            if (ModelState.IsValid)
            {

                workerPayments.TotalWorkHour = t.TotalWorkHour;
                workerPayments.TotalPayment = t.TotalPayment;
                if (t.WorkerPictur != null)
                {
                    string ext = Path.GetExtension(t.WorkerPictur.FileName);
                    string f = Guid.NewGuid() + ext;
                    t.WorkerPictur.SaveAs(Server.MapPath("~/Uploads/") + f);
                    workerPayments.WorkerPictur = f;
                }

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CurrentPic = workerPayments.WorkerPictur;
            ViewBag.Batches = db.workerPayments.ToList();
            return View(t);
        }
        public ActionResult Delete(int id)
        {
            return View(db.workerPayments.Include(x => x.Worker).First(x => x.PaymentId == id));
        }
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirm(int id)
        {
            WorkerPayment t = new WorkerPayment { PaymentId = id };
            db.Entry(t).State = EntityState.Deleted;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

House_Utiliti_Service/Views/WorkerPayments/Create.cshtml
@model House_Utiliti_Service.ViewModels.PaymentInputModel
@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("Create", "WorkerPayments", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.WorkerPictur, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.WorkerPictur, new { @class = "form-control form-control-sm", type = "file" })
                    @Html.ValidationMessageFor(x => x.WorkerPictur, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.WorkerId, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.DropDownListFor(x => x.WorkerId, new SelectList(ViewBag.Workers, "WorkerId", "WorkerName"), "Select", new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.WorkerId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.TotalWorkHour, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.TotalWorkHour, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.TotalWorkHour, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.TotalPayment, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.TotalPayment, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.TotalPayment, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row mb-1">

                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </div>
        }
    </div>
</div>
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>



}

House_Utiliti_Service/Views/WorkerPayments/Delete.cshtml
@model House_Utiliti_Service.Models.WorkerPayment
@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-12">
        <h3>Are you sure to delete?</h3>

        @Html.HiddenFor(x => x.PaymentId)
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.TotalWorkHour, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.TotalWorkHour)

            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.TotalPayment, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.TotalPayment)

            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.Worker, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                @Html.DisplayFor(x => x.Worker.WorkerName)

            </div>
        </div>
        <div class="form-group row mb-1">
            @Html.LabelFor(x => x.WorkerPictur, new { @class = "col-form-label col-form-label-sm col-2" })
            <div class="col-4">
                <img src="~/Uploads/@Model.WorkerPictur" class="img-thumbnail" style="width:50px" />

            </div>

        </div>

        @using (Html.BeginForm("Delete", "WorkerPayments", new { id = Model.PaymentId }, FormMethod.Post))
        {

            <div class="col-4 offset-2">
                <button type="submit" class="btn btn-danger">Confirm Delete</button>

            </div>
        }
        <div class="col-12">

            @Html.ActionLink("Back to list", "Index")
        </div>
    </div>
</div>

House_Utiliti_Service/Views/WorkerPayments/Edit.cshtml
@model House_Utiliti_Service.ViewModels.PaymentEditModel
@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-12">
        @using (Html.BeginForm("Edit", "WorkerPayments", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.HiddenFor(x => x.PaymentId)
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.WorkerPictur, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.WorkerPictur, new { @class = "form-control form-control-sm", type = "file" })
                    @Html.ValidationMessageFor(x => x.WorkerPictur, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-1">
                <img src="~/Uploads/@ViewBag.CurrentPic" class="img-thumbnail" style="width:50px" />
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.WorkerId, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.DropDownListFor(x => x.WorkerId, new SelectList(ViewBag.Workers, "WorkerId", "WorkerName"), "Select", new { @class = "form-select form-select-sm" })
                    @Html.ValidationMessageFor(x => x.WorkerId, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.TotalWorkHour, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.TotalWorkHour, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.TotalWorkHour, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row mb-1">
                @Html.LabelFor(x => x.TotalPayment, new { @class = "col-form-label col-form-label-sm col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.TotalPayment, new { @class = "form-control form-control-sm" })
                    @Html.ValidationMessageFor(x => x.TotalPayment, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row mb-1">

                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-success">Save</button>
                </div>
            </div>
        }
    </div>
<div class="col-12">

    @Html.ActionLink("Back to list", "Index")
</div>
</div>
@section scripts{
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>



}

House_Utiliti_Service/Views/WorkerPayments/Index.cshtml
@model IEnumerable<House_Utiliti_Service.Models.WorkerPayment>
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-12">
        <h3>Products</h3>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Add New", "Create", "WorkerPayments", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead class="bg-secondary">
                <tr>
                    <th>@Html.DisplayNameFor(x => x.WorkerPictur)</th>
                    <th>@Html.DisplayNameFor(x => x.Worker.WorkerName)</th>
                    <th>@Html.DisplayNameFor(x => x.TotalWorkHour)</th>
                    <th>@Html.DisplayNameFor(x => x.TotalPayment)</th>

                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var b in Model)
                {
                    <tr>
                        <td><img src="~/Uploads/@b.WorkerPictur" class="rounded-circle" style="width:40px" /></td>
                        <td>@Html.DisplayFor(x => b.Worker.WorkerName)</td>
                        <td>@Html.DisplayFor(x => b.TotalWorkHour)</td>
                        <td>@Html.DisplayFor(x => b.TotalPayment)</td>
                   


                        <td>
                            @Html.ActionLink("Edit", "Edit", "WorkerPayments", new { id = b.PaymentId }, new { @class = "btn btn-secondary btn-sm" })
                            <a href="@Url.Action("Delete", "WorkerPayments", new {id=b.PaymentId})" class="btn btn-danger btn-sm">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>