House_Utiliti_Service/Controllers/WorkAreasController.cs
using House_Utiliti_Service.Models;
using House_Utiliti_Service.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;

namespace House_Utiliti_Service.Controllers
{
    [Authorize]
    public class WorkAreasController : Controller
    {
        private readonly USDbContext db = new USDbContext();
        // GET: TestEntries
        public ActionResult Index()
        {
            var data = db.workAreas
                .Include(x => x.workerAreas.Select(y => y.Worker))
                .ToList();

            return View(data);
        }
        public ActionResult Create()
        {
            ViewBag.workers = db.workers.ToList();
            var data = new WorkAreaInputModel();
            data.workers.Add(new WorkerViewModel());
            return View(data);
        }
        [HttpPost]
        public ActionResult Create(WorkAreaInputModel model)
        {
            if (ModelState.IsValid)
            {
                var et = new WorkArea
                {
                    WorkAreaName = model.WorkAreaName,
                    Skill = model.Skill,
                    
                };
                foreach (var x in model.workers)
                {
                    et.workerAreas.Add(new WorkerArea { WorkerId = x.WorkerId });
                }
                
                db.workAreas.Add(et);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.workers = db.workers.ToList();

            return View(model);
        }
        //public JsonResult GetFee(int id)
        //{
        //    var t = db.workers.FirstOrDefault(x => x.WorkerId == id);
        //    return Json(t == null ? 0 : t.WorkerName,t.Phone,t.Payrate);
        //}
        public ActionResult CreateNewField(WorkAreaInputModel data)
        {
            ViewBag.workers = db.workers.ToList();
            data.workers.Add(new WorkerViewModel());
            return PartialView(data);
        }
    }
}

House_Utiliti_Service/Views/WorkAreas/Create.cshtml
@model House_Utiliti_Service.ViewModels.WorkAreaInputModel
@{
    ViewBag.Title = "Create";
}

<div id="frm">
    <div class="row">
        <div class="col-12">
            <h3>Create new test entry</h3>
            @using (Html.BeginForm("Create", "WorkAreas", FormMethod.Post, new { id = "f", enctype = "multipart/form-data" }))
            {
                <div class="form-group mb-1">
                    @Html.LabelFor(x => x.WorkAreaName, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.TextBoxFor(x => x.WorkAreaName, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.WorkAreaName, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group mb-1">
                    @Html.LabelFor(x => x.Skill, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.TextBoxFor(x => x.Skill, new { @class = "form-control" })
                        @Html.ValidationMessageFor(x => x.Skill, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="d-flex justify-content-between mb-1">
                    <h4>Tests</h4>
                    <button type="button" id="add" class="btn btn-secondary btn-sm">+</button>
                </div>
                for (var i = 0; i < Model.workers.Count; i++)
                {

        <div class="form-group row mb-1">
            @Html.LabelFor(x => Model.workers[i].WorkerId, new { @class = "col-form-label col-2" })
            <div class="col-4">
                @Html.DropDownListFor(x => Model.workers[i].WorkerId, new SelectList(ViewBag.Workers, "WorkerId", "WorkerName"), "Select one", new { @class = "form-select select" })
                @Html.ValidationMessageFor(x => x.WorkAreaName, "", new { @class = "text-danger" })
            </div>
            @*@Html.LabelFor(x => Model.workers[i].Phone, new { @class = "col-form-label col-2" })
            <div class="col-4">

                @Html.TextBoxFor(x => Model.workers[i].Phone, new { @class = "form-control", @readonly = "true" })

            </div>
            @Html.LabelFor(x => Model.workers[i].Payrate, new { @class = "col-form-label col-2" })
            <div class="col-4">

                @Html.TextBoxFor(x => Model.workers[i].Payrate, new { @class = "form-control", @readonly = "true" })

            </div>
            @Html.LabelFor(x => Model.workers[i].IsRunning, new { @class = "col-form-label col-2" })
            <div class="col-4">

                @Html.TextBoxFor(x => Model.workers[i].IsRunning, new { @class = "form-control", @readonly = "true" })

            </div>*@
        </div>


                }
                <div class="form-group mb-1">

                    <div class="col-4 offset-2">
                        <button type="submit" class="btn btn-primary">Save</button>

                    </div>
                </div>
            }
        </div>
    </div>
</div>
@section styles {
    <style>
        .col2 {
            display: grid;
            grid-template-columns: 2fr 1fr 2fr 1fr
        }
    </style>
}
@section scripts {
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script>
        $(() => {
            $('.select').change(function () {
                var p = $(this).attr("id").split("__")[0];
                console.log($(this).val());
                $.ajax({
                    type: "POST",
                    url: '/WorkArea/GetFee/' + $(this).val(),
                    dataType: "json",
                    success: data => {
                        console.log(data);
                        $(`#${p}__Phone`).val(data);
                    }
                })
            });
            $("#add").click(() => {
                var data = $("#f").serialize();
                console.log(data);
                $.ajax({
                    type: "POST",
                    url: "/WorkAreas/CreateNewField",

                    data: data,
                    success: r => {
                        $("#frm").html(r);
                    }

                });
            });
        });
    </script>
}

House_Utiliti_Service/Views/WorkAreas/CreateNewField.cshtml
@model House_Utiliti_Service.ViewModels.WorkAreaInputModel
<div class="row">
    <div class="col-12">
        <h3>Create new test entry</h3>
        @using (Html.BeginForm("Create", "WorkAreas", FormMethod.Post, new { id = "f", enctype = "multipart/form-data" }))
        {
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.WorkAreaName, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.WorkAreaName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.WorkAreaName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group mb-1">
                @Html.LabelFor(x => x.Skill, new { @class = "col-form-label col-2" })
                <div class="col-4">
                    @Html.TextBoxFor(x => x.Skill, new { @class = "form-control" })
                    @Html.ValidationMessageFor(x => x.Skill, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="d-flex justify-content-between mb-1">
                <h4>Tests</h4>
                <button type="button" id="add" class="btn btn-secondary btn-sm">+</button>
            </div>
            for (var i = 0; i < Model.workers.Count; i++)
            {

                <div class="form-group row mb-1">
                    @Html.LabelFor(x => Model.workers[i].WorkerId, new { @class = "col-form-label col-2" })
                    <div class="col-4">
                        @Html.DropDownListFor(x => Model.workers[i].WorkerId, new SelectList(ViewBag.workers, "WorkerId", "WorkerName"), "Select one", new { @class = "form-select select" })
                        @Html.ValidationMessageFor(x => x.WorkAreaName, "", new { @class = "text-danger" })
                    </div>
                    @*@Html.LabelFor(x => Model.workers[i].WorkerName, new { @class = "col-form-label col-2" })
                    <div class="col-4">

                        @Html.TextBoxFor(x => Model.workers[i].WorkerName, new { @class = "form-control", @readonly = "true" })

                    </div>
                    @Html.LabelFor(x => Model.workers[i].Phone, new { @class = "col-form-label col-2" })
                    <div class="col-4">

                        @Html.TextBoxFor(x => Model.workers[i].Phone, new { @class = "form-control", @readonly = "true" })

                    </div>
                    @Html.LabelFor(x => Model.workers[i].Payrate, new { @class = "col-form-label col-2" })
                    <div class="col-4">

                        @Html.TextBoxFor(x => Model.workers[i].Payrate, new { @class = "form-control", @readonly = "true" })

                    </div>
                    @Html.LabelFor(x => Model.workers[i].IsRunning, new { @class = "col-form-label col-2" })
                    <div class="col-4">

                        @Html.TextBoxFor(x => Model.workers[i].IsRunning, new { @class = "form-control", @readonly = "true" })
                        }
                    </div>*@
                </div>
            }
            <div class="form-group mb-1">

                <div class="col-4 offset-2">
                    <button type="submit" class="btn btn-primary">Save</button>

                </div>
            </div>
        }
    </div>

</div>

House_Utiliti_Service/Views/WorkAreas/Index.cshtml
@model IEnumerable<House_Utiliti_Service.Models.WorkArea>
@{
    ViewBag.Title = "Index";
}
<div class="row">
    <div class="col-12">
        <h3>Test Records</h3>
        <div class="d-flex justify-content-end mb-1">
            @Html.ActionLink("Create New", "Create", new { }, new { @class = "btn btn-primary btn-sm" })
        </div>
        <table class="table table-bordered">
            <thead class=" bg-secondary">
                <tr>
                    <th>@Html.DisplayNameFor(t => t.WorkAreaName)</th>
                    <th>@Html.DisplayNameFor(t => t.Skill)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var x in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(t => x.WorkAreaName)</td>
                        <td>@Html.DisplayFor(t => x.Skill)</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td class="border-end-0">&nbsp;</td>
                        <td colspan="6" class="border-start-0">
                            <h4>Test</h4>
                            <table class="table table-bordered">
                                <thead class=" bg-secondary">
                                    <tr>
                                        <th>Worker Name</th>
                                        <th>Phone</th>
                                        <th>Payrate</th>
                                        <th>IsRunning</th>
                                    </tr>
                                </thead>
                                @foreach (var y in x.workerAreas)
                                {
                                    <tr>
                                        <td>@y.Worker.WorkerName</td>
                                        <td>@y.Worker.Phone</td>
                                        <td>@y.Worker.Payrate</td>
                                        <td>@y.Worker.IsRunning</td>
                                    </tr>
                                }
                                @*<tr>
                                    <td colspan="2" class="text-end pe-2">
                                        Total: @x.workerAreas.Sum(t => t.Worker.WorkerName,)
                                    </td>
                                </tr>*@
                            </table>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>